@startuml 13-strategy
!pragma layout smetana
title Strategy — Comportement
skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam defaultFontName Arial
hide circle
hide empty members

class Panier {
  -paiement : Paiement
  +setPaiement(p : Paiement)
  +checkout()
}
interface Paiement <<interface>> {
  +payer(montant : double)
}
class PaiementCB
class PaiementPaypal
class PaiementCrypto

Panier o-- Paiement : délègue
Paiement <|.. PaiementCB
Paiement <|.. PaiementPaypal
Paiement <|.. PaiementCrypto

legend bottom left
**But :** encapsuler des algorithmes interchangeables.
 
**Lecture :** ""Panier"" a un attribut de type **interface** ""Paiement"" (◇). ""checkout()""
appelle ""paiement.payer()"" sans savoir si c'est une CB ou PayPal. Pour changer d'algo, on
appelle ""setPaiement(...)"", même en cours d'exécution.
endlegend
@enduml
